spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fintech?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: fintech
    password: 1234qwer!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  profiles:
    active: local

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
